#!/usr/bin/env bash

# This script displays the time for 12 hours and 59 minutes:
# minutes are displayed first and then hours

# Display minutes from 1 to 59
min=1
while [ $min -lt 60 ]; do
  echo $min
  min=$(($min+1))
done

# Display hours from 0 to 12
hour=0
while [ $hour -lt 12 ]; do
  echo "Hour: $hour"
  hour=$(($hour+1))
done
